server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-auth-code:
            provider: bonc
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            #redirect-uri: "{baseUrl}/authorized"
            redirect-uri: "http://localhost:8080/client/account/redirect"
            scope: message.read,message.write
#          messaging-client-client-creds:
#            provider: bonc
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: client_credentials
#            scope: message.read,message.write
#          messaging-client-password:
#            provider: bonc
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: password
#            scope: message.read,message.write
        provider:
          bonc:
            authorization-uri: http://localhost:8090/oauth2/authorize
            token-uri: http://localhost:8090/oauth2/token
            jwk-set-uri: http://localhost:8090/auth/jwks

messages:
  base-uri: http://localhost:8092/messages
